//
//  MainInteractor.swift
//  location_activity
//
//  Created phattarapon on 21/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import MapKit
import CoreLocation
import CoreMotion

class MainInteractor: CLLocationManager, CLLocationManagerDelegate {

    weak var presenter: MainPresenterProtocol?
    let locationManager = CLLocationManager()
    let motionActivityManager = CMMotionActivityManager()
}

extension MainInteractor: MainInteractorProtocol {
    
    func addLocationObserver() {
        NotificationCenter.default.addObserver(self, selector: #selector(onLocationNotificationUpdated(notification:)), name: .LocationHelperDidUpdatedSelectedLocation, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(onLocationNotificationError(notification:)), name: .LocationHelperDidError, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(onActivityMotionNotificationUpdated(notification:)), name: .ActivityMotionHelper, object: nil)
    }
    
    @objc func onLocationNotificationUpdated(notification: Notification) {
        if let location = notification.object as? Location {
            self.presenter?.notifyLocationFetched(location: location)
            //self.fetchLocationAuthorizationUpdated()
        }
    }
    
    @objc func onActivityMotionNotificationUpdated(notification: Notification) {
        if let motion = notification.object as? CMMotionActivity {
            let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd HH:mm"
            let date = dateFormatter.string(from: motion.startDate)
            self.presenter?.notifyDisplayMotionData(motion: motion, date: date)
        }
    }
    
    @objc func onLocationNotificationError(notification: Notification) {
        if let err = notification.object as? Error {
            print("Location error = \(err)")
        }
    }
    
    func fetchHistoryActivity() {
        let activity = DBActivityHelper().selectActivityData()
        self.presenter?.notifyFetchHistoryActivity(activity: activity)
    }
    
    func fetchLocation() {
        if Reachability.isConnectedToNetwork() {
            OldLocationHelper.shared().update()
        } else {
            if let location =  OldLocationHelper.shared().location {
               self.presenter?.notifyLocationFetched(location: location)
            } else {
                print("The Internet connection appears to be offline.")
            }
        }
    }
    
    func insertHistoryActivity(activity: ActivityForm) {
        DBActivityHelper.insertActivity(historyActivity: activity)
    }
    
//    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
//        let location = locations.last! as CLLocation
//        let speed: Double = 3.6 * location.speed
//
//        print("speed = \(speed)")
//
//        if speed < 0 {
//            self.presenter?.notifyDisplayGPSSpeed(speed: 0)
//        } else {
//            self.presenter?.notifyDisplayGPSSpeed(speed: speed)
//        }
//    }
}
