//
//  MainViewController.swift
//  location_activity
//
//  Created phattarapon on 21/7/2565 BE.
//  Copyright © 2565 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MainViewController: UIViewController {

	var presenter: MainPresenterProtocol?

    @IBOutlet weak var activityNameLabel: UILabel!
    @IBOutlet weak var dateLabel: UILabel!
    @IBOutlet weak var confidentLabel: UILabel!
    @IBOutlet weak var gpsSpeedLabel: UILabel!
    @IBOutlet weak var locationLabel: UILabel!
    @IBOutlet weak var collectionView: UICollectionView!
    
    var activityFecthData = [ActivityForm]()
    var activityData: String?
    var dateData: String?
    var confidentData: String?
    var speedData: Double?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.presenter?.notifyViewDidLoad()
        self.initUI()
        self.prepareInsertHistoryActivity()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        self.presenter?.notifyViewDidAppear()
    }
    
    func initUI() {
        self.setupNavigationBar()
        let nibActivityCell = UINib(nibName: "MainCollectionViewCell", bundle: nil)
        self.collectionView.register(nibActivityCell, forCellWithReuseIdentifier: "MainCollectionViewCell")
        self.collectionView.register(UINib.init(nibName: "MainHeader", bundle: Bundle.main), forSupplementaryViewOfKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header")
    }
    
    func setupNavigationBar() {
        self.navigationItem.title = "Activity Motion Detect"
    }
    
    func prepareInsertHistoryActivity() {
        if let activity = self.activityData,
           let date = self.dateData,
           let confident =  self.confidentData,
           let speed = self.speedData {
                let activityForm = ActivityForm(activity: activity,
                                                date: date,
                                                confident: confident,
                                                speed: speed)
                
                self.presenter?.notifyInsertHistoryActivity(activity: activityForm)
            }
        self.presenter?.selfFetchActivity()
        self.collectionView.reloadData()
    }
}

extension MainViewController:  MainViewProtocol {
    
    //MARK: location not show and save
    func displayLocationView(location: Location) {
        print("location = \(location)")
        self.locationLabel.text = location.geocoder
    }
    
    func displayGpsSpeed(speed: Double) {
        self.gpsSpeedLabel.text = String(format: "ความเร็ว = %.1f", speed) + " Km/h"
        self.speedData = speed
    }
    
    func displayMotionData(date: String, activity: String) {
        //MARK: การเช็คเปลี่ยนกิจกรรมยังไม่เสรียถ เเละยังเก็บเบื้องหลังไม่ได้
        if activity != activityData {
            self.collectionView.reloadData()
            self.prepareInsertHistoryActivity()
        } else {
            self.collectionView.reloadData()
            print("activity not change = not insert to database")
        }
        
        self.dateLabel.text = "วันที่เริ่ม = \(date)"
        self.activityNameLabel.text = activity
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
            self.dateData = date
            self.activityData = activity
        }
    }
    
    func displayConfidentActivity(confident: String) {
        self.confidentLabel.text = "ความเเม่นยำ = \(confident)"
        self.confidentData = confident
    }
    
    func displayActivityFetch(activity: [ActivityForm]) {
        self.activityFecthData = activity
    }
    
    func showLocationDisabledPopUp() {
        let alertController = UIAlertController(title: "Background Location Access Disabled",
                                                message: "The app need location !!!",
                                                preferredStyle: .alert)
        
        let cancelAction = UIAlertAction(title: "Cancel",
                                         style: .cancel,
                                         handler: nil)
        
        alertController.addAction(cancelAction)
        
        let openSettingAction = UIAlertAction(title: "Setting",
                                              style: .default) { (action) in
            if let url = URL(string: UIApplication.openSettingsURLString) {
                UIApplication.shared.open(url, options: [:], completionHandler: nil)
            }
        }
        
        alertController.addAction(openSettingAction)
        self.present(alertController, animated: true, completion: nil)
    }
}

extension MainViewController: UICollectionViewDelegate, UICollectionViewDataSource {
    
    func numberOfSections(in collectionView: UICollectionView) -> Int {
        return self.activityFecthData.count
    }
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 1
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "MainCollectionViewCell", for: indexPath) as! MainCollectionViewCell
        
        cell.displayHistoryActivity(activity: self.activityFecthData[indexPath.section])
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, at indexPath: IndexPath) -> UICollectionReusableView {
        
        let headerView = collectionView.dequeueReusableSupplementaryView(ofKind: UICollectionView.elementKindSectionHeader, withReuseIdentifier: "header", for: indexPath) as! MainHeader
        let text = "กิจกรรมที่ \(self.activityFecthData.count - indexPath.section)"
        headerView.headerLabel.text = text
        return headerView
    }
}

extension MainViewController: UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView,
                        layout collectionViewLayout: UICollectionViewLayout,
                        sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize.init(width: collectionView.frame.width, height: 150)
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, referenceSizeForHeaderInSection section: Int) -> CGSize {
        return CGSize.init(width: UIScreen.main.bounds.width, height: 30)
    }
}
